<?php

namespace Inshore\CareQualityBundle\Repository;

/**
 * CareDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareDataRepository extends \Doctrine\ORM\EntityRepository
{
}
