<?php

namespace Inshore\CareQualityBundle\Repository;

/**
 * DisabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
